### ISSUE TITLE
ZXHN H298A V1.0

### ISSUE THREAD

**Issue by canyesilyurt** [mkst/zte-config-utility#113]
Hello, I am using a ZXHN H298A V1.0 TTN.26_240416 brand model modem. When I run decode.py, I get an error.

[config-2.bin.zip](https://github.com/user-attachments/files/17776906/config-2.bin.zip)

```
Traceback (most recent call last):
  File "/Users/cy/Downloads/zte-config-utility-master-4/examples/decode.py", line 282, in <module>
    main()
  File "/Users/cy/Downloads/zte-config-utility-master-4/examples/decode.py", line 225, in main
    payload_type = zcu.zte.read_payload_type(infile)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cy/Library/Python/3.12/lib/python/site-packages/zcu/zte.py", line 67, in read_payload_type
    payload_header = read_payload(infile, raise_on_error)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cy/Library/Python/3.12/lib/python/site-packages/zcu/zte.py", line 59, in read_payload
    raise ValueError("Payload header does not start with the payload magic.")
ValueError: Payload header does not start with the payload magic.
```

Another method:

```
python3 examples/b64_to_bin.py config
config not found
➜  zte-config-utility-master-4 python3 examples/b64_to_bin.py config.bin
Success!
➜  zte-config-utility-master-4 python3.12 examples/decode.py --serial ZT343654CA564F config.bin config.xml
Detected signature: ZXHN H298A V1.0
Detected payload type 4
Trying to decode Type 4 payload...
Trying key: '8cc72b05705d5c46ZT343654CA564F' iv: '667b02a85c61c786ZT343654CA564F' generated from serial: 'ZT343654CA564F'
Failed to decrypt payload. Tried 1 generated key(s)!
```

**Comment by BoomBookTR** [comment]
same issue for new TTN.26_240416 software version...

**Comment by coolrecep** [comment]
Any update on that?

**Comment by ibrah3m** [comment]
I'm looking for update , I have same problem I'm online and available to provide any needed info and try anything you want
