### ISSUE TITLE
ZTE F600W Error

### ISSUE THREAD

**Issue by vh13294** [mkst/zte-config-utility#14]
I tried to decrypt my own ZTE_F600W_CONFIG.bin.

Got this error:

python3 examples/decode.py resources/ZTE_F600W_DEFAULT.bin resources/ZTE_F600W.xml 
Traceback (most recent call last):
  File "examples/decode.py", line 41, in <module>
    main()
  File "examples/decode.py", line 37, in main
    res, _ = zcu.compression.decompress(infile)
  File "/Users/Library/Python/3.8/lib/python/site-packages/zcu-0.1.0-py3.8.egg/zcu/compression.py", line 28, in decompress
zlib.error: Error -3 while decompressing data: incorrect header check

**Comment by mkst** [comment]
can you share your config.bin?
