### ISSUE TITLE
VC220-G3u

### ISSUE THREAD

**Issue by DogancanYr** [mkst/zte-config-utility#73]
**Description of new feature**
I would like the VC220-G3u to be supported

**Describe alternatives you've considered**
I have tried using --payload xxx but I get the following error 

C:\Users\gokic\Desktop\zte-config-utility-master>py examples/decode.py --serial D4B7092D1339 Config. Bin config.xml
Signature:
Traceback (most recent call last):
 File "C:\Users\gokic\Desktop\zte-config-utility-master\examples\decode.py", line 109, in <module>
 main()
 File "C:\Users\gokic\Desktop\zte-config-utility-master\examples\decode.py", line 44, in main.
 Payload_type = zcu. ZTE. Read_payload_type(infile)
 File "C:\Users\gokic\AppData\Roaming\Python\Python310\site-packages\zcu-0.1.0-py3.10.egg\zcu\zte.py", line 55, in read_payload_type.
 File "C:\Users\gokic\AppData\Roaming\Python\Python310\site-packages\zcu-0.1.0-py3.10.egg\zcu\zte.py", line 47, in read_payload.
ValueError: Payload header does not start with the payload magic.

**Comment by DogancanYr** [comment]
.

**Comment by devjunioralves** [comment]
There was a solution for this problem, I'm having the same problem with the ZTE 6600p
