### ISSUE TITLE
[FEATURE] ZTE F671Y

### ISSUE THREAD

**Issue by directentis1** [mkst/zte-config-utility#78]
**Description of new feature**
e.g. I would like the ZTE F671Y V9.0 router to be supported

**Describe alternatives you've considered**
e.g. I have tried using --payload xxx but I get the following error < error >
```
$ python3 ../examples/decode.py --serial ZTEEQKANBX09531 --signature 'ZXHN F671Y V9.0' config.bin config.xml
Traceback (most recent call last):
  File "/home/xxxx/zte/zte-config-utility/resources/../examples/decode.py", line 194, in <module>
    main()
  File "/home/xxxx/zte/zte-config-utility/resources/../examples/decode.py", line 45, in main
    zcu.zte.read_header(infile)
  File "/home/xxxx/.local/lib/python3.9/site-packages/zcu-0.4.0-py3.9.egg/zcu/zte.py", line 17, in read_header
AssertionError
```

**Additional context**
My router specs: ![](https://i.imgur.com/BGjpWuP.png) 

**Attach config.bin for your device**
Okay, my exported `config.bin`:

[config.bin.zip](https://github.com/mkst/zte-config-utility/files/12266879/config.bin.zip)
(It's not a zip file, please remove the `.zip` extension to get the actual file)

**Comment by mkst** [comment]
The AssertionError should be fixed, however I don't know what the key is to decrypt your config.bin. I assume you do not have telnet access? Is there a firmware available that we could look into?

**Comment by lynh7** [comment]
Hi @mkst, might I ask what's the current status of this model? Thanks

**Comment by lynh7** [comment]
> Hi [@mkst](https://github.com/mkst), might I ask what's the current status of this model? Thanks

nvm, I've frigured it out the PPOE credential with this command 
`python examples/auto.py --serial 'serial_here' --mac 'xx:xx:xx:xx:xx' config.bin config.xml`
