### ISSUE TITLE
ZTE ZXHN H267N V1.1 config.bin "AssertionError"

### ISSUE THREAD

**Issue by nafatrue** [mkst/zte-config-utility#9]
hi i have this config.bin from H267N v1.1 i tried to decode but I have this error "AssertionError", t tried to find the problem but no success.

**i executed info.py it gives me :+1:** 

Signature:          ZXHN H267N V1.1
Payload Type:       4 (UNKNOWN)
Payload Start:      87
Decompressed size:  0 bytes
2nd last chunk:     0
Chunk size:         0 bytes
Payload CRC:        0
Header CRC:         0

**the error I got when I executed decode.py without a key is:**

`Traceback (most recent call last):
  File "examples/decode.py", line 41, in <module>
    main()
  File "examples/decode.py", line 36, in main
    payload_type = zcu.zte.read_payload_type(infile)
  File "/home/user/.local/lib/python3.8/site-packages/zcu-0.1.0-py3.8.egg/zcu/zte.py", line 51, in read_payload_type
  File "/home/user/.local/lib/python3.8/site-packages/zcu-0.1.0-py3.8.egg/zcu/zte.py", line 45, in read_payload
AssertionError`

**i found a key in the internet I used and also no success always same error:**

`python3 examples/decode.py config.bin config.xml --key 'tHG@Ti&GVh@ql3XN'
Traceback (most recent call last):
  File "examples/decode.py", line 41, in <module>
    main()
  File "examples/decode.py", line 36, in main
    payload_type = zcu.zte.read_payload_type(infile)
  File "/home/user/.local/lib/python3.8/site-packages/zcu-0.1.0-py3.8.egg/zcu/zte.py", line 51, in read_payload_type
  File "/home/user/.local/lib/python3.8/site-packages/zcu-0.1.0-py3.8.egg/zcu/zte.py", line 45, in read_payload
AssertionError
`

please any chance to solve this I want to change router from the company and they are hiding DSL authentication credentials username and password for DATA and SIP.

i attached the config.bin file in a zip file I hope you help me in this thank you in advance
[config.zip](https://github.com/mkst/zte-config-utility/files/5635814/config.zip)

**Comment by olivluca** [comment]
I don't know if it means anything but the payloat type 4 is the same as my router, so you could try the --serial option instead of the --key one (after --serial you should specify the serial number of your router).
Oh, and if your internet provider is like mine, they have modified the firmware so that there's no voip credentials in the config.bin file (but if the --serial option works I can tell you a possible way to get it).

**Comment by nafatrue** [comment]
yes the firmware is modified by the provider I can't get credentials of DATA & SIP i already tried the --serial option but no success I don't know if it is necessary to use Read_payload to decode the config.bin file.

**Comment by olivluca** [comment]
Yes, probably they used a different encryption scheme or a different password, sorry.

**Comment by nafatrue** [comment]
yes definitely that's the problem encryption i searched to find AES encryption key but no success till now

**Comment by yvsser1** [comment]
@nafatrue any luck with that problem i have the same router and i really need the user/pass ?

**Comment by samtimber** [comment]
This tools will not work for you ,
You are lucky my friends because you have the same router as i have .i did some work on it lately (dumping the 128m nand and analyzing the cspd file) and it was very easy .
if you want what inside the config send me the config.bin file to my email : rianne.nedof@gmail.com and i will send you back what you want for free.
do not post the config.bin here because it's contain your ISP informations that someone could use

**Comment by yvsser1** [comment]
@samtimber i sent you an email with the config file included, my email is yvsser1@gmail.com thank you !!

**Comment by geoleven** [comment]
> This tools will not work for you , You are lucky my friends because you have the same router as i have .i did some work on it lately (dumping the 128m nand and analyzing the cspd file) and it was very easy . if you want what inside the config send me the config.bin file to my email : [rianne.nedof@gmail.com](mailto:rianne.nedof@gmail.com) and i will send you back what you want for free. do not post the config.bin here because it's contain your ISP informations that someone could use

Could you please share the process so we could individually do it and also have the info in case you are not available at some point?

**Comment by yvsser1** [comment]
thanks to @samtimber the config file for my ZTE ZXHN H267N is decrypted

**Comment by mkst** [comment]
This tool is open source to benefit anyone and everyone interested in having more control over their ZTE hardware. Please help improve the tool by sharing your knowledge @samtimber

**Comment by mstDr** [comment]
@samtimber i sent you an email with the config file included, my email is ahazmuta@gmail.com
thank you !! and forgive me for the inconvenience

**Comment by mstDr** [comment]
thanks to @samtimber

**Comment by kies83** [comment]
Take a look at pm? @samtimber

**Comment by HeXGmR** [comment]
@kies83 need your help pm me ur discord :)

**Comment by AchDaw** [comment]
@samtimber i sent you an email with the config file, can you please decrypte it and send me back the pppoe username and password. Thanks

**Comment by AchDaw** [comment]
Still no response from amtimber

**Comment by AchDaw** [comment]
Thank you very much samtimber config file is decrypted

**Comment by AlbertKirkovich** [comment]
> 
Hi, @samtimber!
Can i send You config.bin file for decrypton??

**Comment by AlbertKirkovich** [comment]
Hi, @samtimber !
Thank you so much for decrypt!
Sincerely,
Pavel.

**Comment by Markos33** [comment]
@samtimber
If you could reply to the email (markosluk...) I sent you 7 days ago with the decrypted information, I would appreciate it.

**Comment by FrankieTankie** [comment]
@samtimber, do you still provide help?
It would be appreciated.
Regards

**Comment by mkst** [comment]
Can you try using the latest version of the repo, also can you try the `examples/auto.py` script?

**Comment by Markos33** [comment]
Thank you for the question but unfortunately, I don't have that router
anymore.
All the best!

**Comment by AlbertKirkovich** [comment]
I have one H267N V1.1 left, checked the script auto.py - it works!

C:\Install\Python\Python313>python auto.py config_router12.bin ccc.bin
Successfully decrypted and decompressed config_router12.bin using (key, iv): ('ZXHNH267NV1.1Key02721401', 'ZXHNH267NV1.1Iv02721401')

ccc.bin file is read successfully.
Thanks a lot!
